web-design-project-2025/web-design-project-group-30

.vscode/settings.json
css/main.css
index.html

so I did the fundamental homepage layout with the header, main, and footer which we can built upon by adding CSS

Homepage layout branch

---

index.html
js/main.js

It's clickable for now, but it's not adjusted specifically to smaller screens yet.

Hamburger menu (not complete)

---

css/main.css

It's just a little extra feature that came to my mind, but I just added like 3 lines of code.

added a small zoom as the user hovers over a movie thumbnail

---

css/main.css
detailed-movie-review-page.html

I created the basic layout for this page so we can use it for all the detailed pages with some customization. I used Flexbox to align the "headers" like the movie poster: the title, the heart, and the stars. Further, I will add the features to the page.

Detailed movie review page layout

---

css/main.css
profile.html

added the layout for the mobile profile page, images still needs to be added

The layout for the profile page

---

detailed.json
movie.json

Added the json for Bothe the movie.json and detailed.json, the detailed.json is for the detailed page and the movie.json is for the over look

added the json 

---

css/main.css
js/detailed.js
js/favourite.js

#64 Pictures are now able to load to the favorites page

Bug fixing

---

js/avatarapi.js

#49 Added an error handling that is meaningful (I hope)

Added the error handling of the API

---

css/editorial.css
editorial.html
index.html

#46 made the editorial and responsiveness for it

Editorial text

---

css/main.css

made the responsiveness for the homepage

responsiveness homepage

---

action.html
comedy.html
documentary.html
horror.html
romance.html
science-fiction.html

#85 adding category buttons to the category pages

adding category buttons to each category

---

.vscode/settings.json
css/detailed-movie.css

adjustments made

---

action.html
allmovie.html
classics.html
comedy.html
css/main.css
documentary.html
editorial.html
favourite.html
horror.html
index.html
js/detailed.js
js/main.js
profile.html
romance.html
science-fiction.html
trending.html

made a fixed navigation for all pages

---

data/detailed.json

#93 loading images on detailed page from classics page

making sure the classic movies loads on detailed page

---

css/detailed-movie.css
js/detailed.js

Responsiveness detailed page fix

---

allmovie.html
css/detailed-movie.css

Bug fix allmovies

---

css/editorial.css
editorial.html

added design fixes tot he editorial page

---

action.html
allmovie.html
comedy.html
css/category.css
documentary.html
romance.html
science-fiction.html

Category design fixes

---

css/main.css
css/profile.css

making sure all the buttons have the same colours when hovering

---

allmovie.html
css/detailed-movie.css
css/favoutite.css
css/filters.css
css/main.css
index.html
js/detailed.js

most adjustments done + added a return button to the trending page. hamburger menu needs some alignment fixes between text and icons and the review box in trending needs to be adjusted for smaller screens

Adjustments

---

css/main.css
css/trending.css

added responsiveness for the category buttons, heading and nav bar #100

Final responsiveness

---

css/classics.css
css/detailed-movie.css
css/favoutite.css
css/profile.css
css/trending.css
favourite.html

Added some animation and put spacing on profile page

Small changes
